
import java.awt.Color;
import java.awt.Rectangle;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Msi
 */
public class symptomes extends javax.swing.JFrame {
MyConnection conn2=new MyConnection();
    Statement stm2;
    ResultSet Rs2;
    JCheckBox []roll = new JCheckBox[100];
    
    int X,Y,K;
    /**
     * Creates new form test
     */
    public symptomes() {
        initComponents();
        this.setLocationRelativeTo(null);
        remplircheckbox();
        getContentPane().setBackground(new Color(153, 153, 255));
        
    }
public void remplircheckbox(){
    PreparedStatement ps;
    ResultSet rs;
   String query = "SELECT symptome FROM symptomes";
 try {
            ps = MyConnection.getConnection().prepareStatement(query);
            
       
            
                   
            
            
             rs = ps.executeQuery();
            
           while (rs.next())
           {
             roll[K] = new JCheckBox();
             roll[K].setText(rs.getString("symptome"));
             roll[K].setBounds(X,Y,500,50);
             Y=Y+30;
             
             
             Rectangle r=this.getBounds();
             int h=r.height;
             if(Y>=h-50)
             {Y=100;
              X=X+200;
             }
             this.add(roll[K]);
             K++;
               
           }
           } catch (SQLException ex) {
            Logger.getLogger(symptomes.class.getName()).log(Level.SEVERE, null, ex);
        }}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));

        jButton1.setBackground(new java.awt.Color(34, 167, 240));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Valider");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Veuillez choisir vos symtomes afin d'identifier votre maladie :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(176, 176, 176))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 602, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    if (roll[0].isSelected() && roll[1].isSelected()|| roll[2].isSelected() || roll[3].isSelected() || roll[4].isSelected() && roll[5].isSelected()){
        JOptionPane.showMessageDialog(null,"Utiliser le reference A11 dans le champ ci dessous pour savoir plus sur votre maladie et le traitement");
        maladie rgf = new maladie();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null); // Affichage au milieu
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose(); //Fermer la page precedente
            }
    if (roll[6].isSelected() || roll[7].isSelected()){
        JOptionPane.showMessageDialog(null,"Utiliser le reference M11 dans le champ ci dessous pour savoir plus sur votre maladie et le traitement");
        maladie rgf = new maladie();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null); // Affichage au milieu
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose(); //Fermer la page precedente
        
    }
    if (roll[8].isSelected() || roll[9].isSelected()|| roll[10].isSelected() && roll[11].isSelected() ){
       JOptionPane.showMessageDialog(null,"Utiliser le reference S11 dans le champ ci dessous pour savoir plus sur votre maladie et le traitement");
        maladie rgf = new maladie();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null); // Affichage au milieu
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose(); //Fermer l
            }
    if (roll[10].isSelected() && roll[12].isSelected() || roll[13].isSelected() && roll[14].isSelected() && roll[15].isSelected() ){
        JOptionPane.showMessageDialog(null,"Utiliser le reference B11 dans le champ ci dessous pour savoir plus sur votre maladie et le traitement");
        maladie rgf = new maladie();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null); // Affichage au milieu
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose(); //Fermer l
            }
    if (roll[16].isSelected() || roll[17].isSelected()|| roll[18].isSelected() && roll[5].isSelected() ){
        JOptionPane.showMessageDialog(null,"Utiliser le reference C11 dans le champ ci dessous pour savoir plus sur votre maladie et le traitement");
        maladie rgf = new maladie();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null); // Affichage au milieu
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose(); //Fermer l
            }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(symptomes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(symptomes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(symptomes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(symptomes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new symptomes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
